[package]
name = "winisland-core"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
base64 = "0.23.1"
educe = { version = "0.7", default-features = false, features = ["Default"] }
encoding_rs = "0.8"
fuzzengine = "0.2.1"
log = { version = "0.4", features = ["std"] }
lrc = "0.2.0"
parking_lot = "0.12"
quick-xml = "0.41.0"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
settings-schema = { path = "../settings-schema" }
strum = { version = "0.28", features = ["derive"] }
toml = "1.1.2"
